-- 054_wiki_templates_richer.sql
-- Kullanıcı geri bildirimi: "şablonların içi berbat, confluencea asla
-- yanaşamaz." Gerçek Confluence şablonlarının web'de araştırılan asıl
-- yapısına göre (atlassian.com/software/confluence/templates/*, DACI
-- Team Playbook, retrospective rehberleri) TÜM şablonlar yeniden
-- yazıldı: rehber cümleler, gerçek alt başlıklar, örnek tablo satırları
-- ve Confluence'ın kendi şablonlarındaki soru-cevap tarzı yönlendirme
-- metinleri eklendi — artık yalnızca boş etiket+iki nokta değil.
UPDATE wiki_page_templates SET content = E'# Proje Analizi: \n\n**Proje:** \n**Analiz Tarihi:** \n**Analiz Eden:** \n\n> Bu sayfa, devam eden bir projenin durumunu tarafsız bir gözle değerlendirmek için kullanılır. Amaç suçlamak değil, erken uyarı sinyallerini yakalamaktır.\n\n## Mevcut Durum Özeti\n_Proje şu anda nerede? Plana göre önde mi, geride mi?_\n\n\n## Kapsam ve Hedeflere Uygunluk\n_Başlangıçta belirlenen hedeflerden saptık mı? Kapsam kaydı (scope creep) var mı?_\n\n\n## Zaman Çizelgesi Değerlendirmesi\n| Kilometre Taşı | Planlanan | Gerçekleşen/Tahmini | Sapma |\n|---|---|---|---|\n| | | | |\n\n## Bütçe Değerlendirmesi\n_Harcanan / Kalan / Tahmini toplam._\n\n\n## Riskler ve Sorunlar\n| Risk/Sorun | Olasılık | Etki | Önerilen Aksiyon | Sahibi |\n|---|---|---|---|---|\n| | | | | |\n\n## Genel Değerlendirme ve Tavsiyeler\n_Projeye devam mı, yön değişikliği mi, yoksa durdurma mı önerilir? Gerekçesiyle birlikte yazın._\n'
WHERE name='Proje Analizi';

UPDATE wiki_page_templates SET content = E'# Retrospective: \n\n**Sprint/Dönem:** \n**Tarih:** \n**Katılımcılar:** \n\n## Amaç\n_Bu retrospektifin amacını bir cümleyle özetleyin — ör. "Son sprint''teki teslimat gecikmelerinin kök nedenini bulmak."_\n\n## Arka Plan\n_Bu dönemde neler teslim edildi/yaşandı? 2-3 cümlelik kısa bir özet, herkesin hafızasını tazelemesi için._\n\n## Beğendiklerim (Loved)\n_Bu dönem keyif aldığımız, tekrar etmek istediğimiz şeyler._\n- \n\n## Öğrendiklerim (Learned)\n_Yeni fark ettiğimiz, öğrendiğimiz şeyler._\n- \n\n## Eksik Kalanlar (Lacked)\n_İhtiyaç duyduğumuz ama sahip olmadığımız şeyler (araç, bilgi, zaman, destek)._\n- \n\n## Özlediklerim (Longed for)\n_Keşke olsaydı dediğimiz şeyler._\n- \n\n## Aksiyon Maddeleri\n| Aksiyon | Sorumlu | Hedef Tarih | Durum |\n|---|---|---|---|\n| | | | Açık |\n\n## Kapanış Notları\n_Bir sonraki dönemde neyi farklı yapacağız?_\n'
WHERE name='Retrospective (4L)';

UPDATE wiki_page_templates SET content = E'# 1:1 Toplantısı\n\n**Katılımcılar:** \n**Tarih:** \n\n## Gündem\n_Her iki taraf da toplantıdan önce madde ekleyebilir._\n- \n\n## Geri Bildirim\n_Karşılıklı, yapıcı geri bildirim — hem takdir hem gelişim alanları._\n\n\n## Kariyer/Gelişim Notları\n_Uzun vadeli hedefler, öğrenme planı, ilerleme._\n\n\n## Önceki Aksiyonların Takibi\n_Bir önceki 1:1''de kararlaştırılan maddeler ne durumda?_\n- \n\n## Aksiyon Maddeleri\n| Aksiyon | Sorumlu | Hedef Tarih |\n|---|---|---|\n| | | |\n'
WHERE name='1:1 Toplantısı';

UPDATE wiki_page_templates SET content = E'# Proje Açılış Toplantısı: \n\n**Proje:** \n**Tarih:** \n**Sponsor:** \n\n## Proje Amacı\n_Bu proje neden yapılıyor? Hangi iş problemini çözüyor?_\n\n## Kapsam\n**Kapsamda:**\n- \n\n**Kapsam Dışı:**\n- \n\n## Ekip ve Roller\n| Rol | Kişi | Sorumluluk |\n|---|---|---|\n| Proje Yöneticisi | | |\n| Sponsor | | |\n| Geliştirici(ler) | | |\n\n## Zaman Çizelgesi ve Kilometre Taşları\n| Kilometre Taşı | Hedef Tarih |\n|---|---|\n| | |\n\n## Başarı Kriterleri\n_Bu proje ne zaman "başarılı" sayılacak? Ölçülebilir kriterler yazın._\n- \n\n## Riskler ve Bağımlılıklar\n_Başlangıçta görülen riskler ve dış bağımlılıklar._\n- \n\n## Açık Sorular\n_Henüz netleşmemiş, takip edilmesi gereken konular._\n- \n'
WHERE name='Proje Açılış (Kickoff) Toplantısı';

UPDATE wiki_page_templates SET content = E'# Proje Poster: \n\n**Durum:** 🟡 Planlama\n\n| | |\n|---|---|\n| **Proje Sahibi** | |\n| **Ekip Üyeleri** | |\n\n## Problem Alanı\n**Problem tanımı:** _Çözmeye çalıştığımız sorun ne?_\n\n**Bu sorunun etkisi:** _Çözülmezse ne olur?_\n\n**Bu proje daha geniş stratejiye nasıl uyuyor?**\n\n\n## Ne Zaten Biliyoruz?\n_Bu konuda elimizdeki mevcut veri, önceki denemeler, kullanıcı geri bildirimi._\n\n\n## Ne Yapıyoruz?\n_Kısa, net bir çözüm özeti._\n\n\n## Neden Bir Müşteri Bunu İstesin?\n\n\n## Doğrulama\n_Bu çözümün doğru olduğunu nasıl doğrulayacağız? (Kullanıcı testi, pilot, veri analizi vb.)_\n\n\n## Ölçek ve Kapsam\n_Gereken ekip büyüklüğü, süre, bütçe tahmini._\n\n\n## Neyi Cevaplamamız Gerekiyor?\n_Henüz cevaplanmamış açık sorular._\n- \n'
WHERE name='Proje Poster';

UPDATE wiki_page_templates SET content = E'# Proje Durum Raporu — \n\n**Proje:** \n**Rapor Tarihi:** \n**Genel Durum:** 🟢 Yolunda\n\n## Yönetici Özeti\n_1-2 cümlede: bu dönem neler oldu, en önemli nokta ne?_\n\n## Bu Dönem Tamamlananlar\n- \n\n## Sıradaki Adımlar\n- \n\n## Riskler / Engeller\n| Risk/Engel | Etki | Öneri | Sahibi |\n|---|---|---|---|\n| | | | |\n\n## Bütçe / Zaman Durumu\n| Metrik | Planlanan | Gerçekleşen | Durum |\n|---|---|---|---|\n| Bütçe | | | |\n| Zaman | | | |\n\n## Karar Gerektiren Konular\n_Yönetimden onay/karar bekleyen maddeler._\n- \n'
WHERE name='Proje Durum Raporu';

UPDATE wiki_page_templates SET content = E'# DACI: [Karar vermeye çalıştığımız soru]?\n\n| | |\n|---|---|\n| **Durum** | Taslak |\n| **Son Karar Tarihi** | |\n| **Sonuç** | _(karar verilince doldurulur)_ |\n\n## DACI Rolleri\n| Rol | Kişi | Açıklama |\n|---|---|---|\n| **D**river | | Süreci yürüten, bilgiyi toplayan kişi |\n| **A**pprover | | Son kararı veren kişi |\n| **C**ontributors | | Görüş bildiren ama oy hakkı olmayanlar |\n| **I**nformed | | Yalnızca sonuçtan haberdar edilecekler |\n\n## Bağlam (Background)\n_Bu kararın neden gerekli olduğunu ve önemini 1-2 cümlede açıklayın._\n\n\n## Mevcut Durum\n_Şu anda neredeyiz?_\n\n\n## Destekleyici Veri\n_Kararı etkileyecek araştırma, veri, kullanıcı geri bildirimi._\n\n\n## Karar Faktörleri\n_Seçenekleri değerlendirirken neye bakacağız? (maliyet, süre, ölçeklenebilirlik, risk...)_\n- \n\n## Değerlendirilen Seçenekler\n| Seçenek | Artıları | Eksileri | Tahmini Maliyet/Efor |\n|---|---|---|---|\n| Hiçbir şey yapma | | | |\n| Seçenek 2 | | | |\n| Seçenek 3 | | | |\n\n## Öneriler\n_Contributors''dan gelen görüşler._\n\n\n## Alınan Karar\n\n\n## Aksiyon Maddeleri\n| Aksiyon | Sorumlu | Tarih |\n|---|---|---|\n| | | |\n'
WHERE name='Karar Kaydı (DACI)';

UPDATE wiki_page_templates SET content = E'# Risk Kaydı (Risk Register)\n\n**Proje:** \n**Güncelleme Tarihi:** \n\n> Olasılık ve Etki için 1 (Düşük) - 5 (Çok Yüksek) arası bir puanlama önerilir; Skor = Olasılık × Etki.\n\n| # | Risk Tanımı | Kategori | Olasılık (1-5) | Etki (1-5) | Skor | Önlem/Aksiyon | Sahibi | Durum |\n|---|---|---|---|---|---|---|---|---|\n| 1 | | Teknik / Zaman / Bütçe / Kaynak | | | | | | Açık |\n\n## Yüksek Öncelikli Riskler (Skor ≥ 15)\n_Yukarıdaki tablodan en kritik olanları buraya taşıyıp detaylandırın._\n\n\n## Kapatılan Riskler\n_Artık geçerli olmayan ya da gerçekleşmeyen riskler, ne zaman ve neden kapatıldığıyla birlikte._\n'
WHERE name='Risk Kaydı (Risk Register)';

UPDATE wiki_page_templates SET content = E'# Ürün Gereksinimleri Dokümanı (PRD): \n\n**Özellik/Ürün:** \n**Sahip:** \n**Durum:** Taslak\n**Son Güncelleme:** \n\n## Problem Tanımı\n_Kullanıcı hangi sorunu yaşıyor? Bu sorunun kanıtı ne (veri, geri bildirim, destek talebi sayısı)?_\n\n## Hedef Kullanıcı / Persona\n_Bu özellik kimin için? Birincil ve ikincil kullanıcı grupları._\n\n## Hedefler ve Başarı Metrikleri\n_Bu özellik başarılı olursa hangi metrik nasıl değişecek?_\n| Metrik | Mevcut | Hedef |\n|---|---|---|\n| | | |\n\n## Kullanıcı Hikayeleri\n_"[Kullanıcı tipi] olarak, [ihtiyaç] istiyorum, çünkü [fayda]."_\n- \n\n## Gereksinimler\n### Zorunlu (Must have)\n- [ ] \n### Olsa iyi olur (Nice to have)\n- [ ] \n\n## Kabul Kriterleri\n_Bu özelliğin "bitti" sayılması için karşılanması gereken somut koşullar._\n- \n\n## Kapsam Dışı\n_Bilinçli olarak bu sürümde YAPILMAYACAK olanlar (beklenti yönetimi için önemli)._\n- \n\n## Açık Sorular\n- \n'
WHERE name='Ürün Gereksinimleri (PRD)';

UPDATE wiki_page_templates SET content = E'# Olay Sonrası İnceleme (Postmortem): \n\n**Olay Tarihi:** \n**Tespit Zamanı:** \n**Çözüm Zamanı:** \n**Etki Süresi:** \n**Ciddiyet:** SEV-\n\n> Bu belge suçlamasız (blameless) bir kültürle yazılır: amaç "kim hata yaptı" değil "sistem neden buna izin verdi"dir.\n\n## Özet\n_2-3 cümlede: ne oldu, kim/ne etkilendi, nasıl çözüldü._\n\n## Etkilenen Sistemler / Kullanıcılar\n\n\n## Zaman Çizelgesi\n| Saat (UTC) | Olay |\n|---|---|\n| | İlk belirti fark edildi |\n| | Olay bildirildi/eskalasyon |\n| | Kök neden bulundu |\n| | Çözüm uygulandı |\n| | Doğrulandı, olay kapatıldı |\n\n## Kök Neden\n_Teknik kök neden. Mümkünse "5 Neden" analizi ile derinleştirin._\n\n## Ne İyi Gitti?\n_Müdahale sırasında işe yarayan şeyler (izleme, runbook, iletişim vb.)._\n- \n\n## Ne Kötü Gitti?\n- \n\n## Alınan Aksiyonlar\n| Aksiyon | Tür (Önleyici/İzleme/Süreç) | Sorumlu | Hedef Tarih |\n|---|---|---|---|\n| | | | |\n\n## Öğrenilen Dersler\n_Bu olaydan takım/organizasyon olarak çıkardığımız genel dersler._\n'
WHERE name='Olay Sonrası İnceleme (Postmortem)';

UPDATE wiki_page_templates SET content = E'# 5 Neden Analizi (5 Whys)\n\n**Problem:** _Gözlemlenen belirtiyi net bir cümleyle yazın._\n\n> Her "Neden?" sorusunun cevabı bir öncekinin kök nedenine inmelidir. 5 bir kural değil, kılavuzdur — kök nedene 3 soruda da ulaşabilirsiniz, 7 soru da gerekebilir.\n\n1. **Neden oldu?** \n2. **Peki bu neden oldu?** \n3. **Peki bu neden oldu?** \n4. **Peki bu neden oldu?** \n5. **Peki bu neden oldu?** \n\n## Kök Neden\n_Zincirin sonundaki, gerçekten çözülmesi gereken temel sebep._\n\n## Bu Kök Nedeni Doğrulayan Kanıt\n_Varsayım değil, veri/gözlem._\n\n## Önerilen Aksiyon\n_Kök nedeni ortadan kaldıracak somut adım(lar)._\n- \n'
WHERE name='5 Neden Analizi (5 Whys)';

UPDATE wiki_page_templates SET content = E'# Beyin Fırtınası: \n\n**Konu/Problem:** _Ne için fikir üretiyoruz? Net bir soru cümlesi yazın._\n\n**Katılımcılar:** \n**Süre:** \n\n> Bu aşamada eleştiri yok — miktar, kaliteden önce gelir. Her fikir, ne kadar "saçma" görünse de yazılır.\n\n## Fikirler\n_Herkes serbestçe ekleyebilir._\n- \n\n## Gruplama / Temalar\n_Benzer fikirleri birlikte kümeleyin._\n\n\n## Değerlendirme Kriterleri\n_Fikirleri neye göre önceliklendireceğiz? (Etki, Uygulanabilirlik, Maliyet vb.)_\n\n\n## Oylama Sonucu (öncelikli fikirler)\n1. \n2. \n3. \n\n## Sonraki Adımlar\n| Aksiyon | Sorumlu | Tarih |\n|---|---|---|\n| | | |\n'
WHERE name='Beyin Fırtınası (Brainstorming)';

UPDATE wiki_page_templates SET content = E'# SWOT Analizi: \n\n**Konu:** \n**Tarih:** \n**Katılımcılar:** \n\n> İç kaynaklı faktörler (Güçlü/Zayıf Yönler) kontrolümüzde olanlardır; dış kaynaklı faktörler (Fırsat/Tehdit) pazardan, rekabetten, regülasyondan gelir.\n\n## Güçlü Yönler (Strengths) — İç, Yardımcı\n_Rakiplere göre avantajımız, iyi yaptığımız şeyler._\n- \n\n## Zayıf Yönler (Weaknesses) — İç, Zararlı\n_İyileştirilmesi gereken, rakiplerin bizden iyi olduğu alanlar._\n- \n\n## Fırsatlar (Opportunities) — Dış, Yardımcı\n_Pazardaki, teknolojideki, düzenlemelerdeki lehimize gelişmeler._\n- \n\n## Tehditler (Threats) — Dış, Zararlı\n_Dışarıdan gelebilecek riskler (rekabet, pazar değişimi, regülasyon)._\n- \n\n## Sonuç ve Öneriler\n_Bu analizden çıkan somut aksiyon önerileri neler?_\n'
WHERE name='SWOT Analizi';

UPDATE wiki_page_templates SET content = E'# Toplantı Notu: \n\n**Tarih:** \n**Katılımcılar:** \n\n## Gündem\n_Toplantı öncesi belirlenen konu başlıkları._\n- \n\n## Notlar\n_Görüşme sırasında alınan notlar, tartışılan konular._\n\n\n## Kararlar\n_Bu toplantıda netleşen kararlar._\n- \n\n## Aksiyon Maddeleri\n| Aksiyon | Sorumlu | Hedef Tarih |\n|---|---|---|\n| | | |\n'
WHERE name='Toplantı Notu';

UPDATE wiki_page_templates SET content = E'# Nasıl Yapılır: \n\n**Son güncelleme:** \n**Sahip:** \n\n## Bu Rehber Ne İçin?\n_Bu adımları kimin, hangi durumda izleyeceğini kısaca açıklayın._\n\n## Ön Koşullar\n_Başlamadan önce gerekli erişim, araç veya bilgi._\n- \n\n## Adımlar\n1. \n2. \n3. \n\n## Beklenen Sonuç\n_Adımlar doğru uygulandığında ne görmeliyiz?_\n\n## Sorun Giderme\n| Belirti | Olası Neden | Çözüm |\n|---|---|---|\n| | | |\n\n## İlgili Kaynaklar\n- '
WHERE name='Nasıl Yapılır (How-to)';

UPDATE wiki_page_templates SET content = E'# Karar Kaydı: \n\n**Tarih:** \n**Karar Sahibi:** \n**Katılımcılar:** \n\n## Bağlam\n_Bu kararın alınmasını gerektiren durum neydi?_\n\n## Değerlendirilen Seçenekler\n- \n\n## Alınan Karar\n\n\n## Gerekçe\n_Bu seçenek neden diğerlerine tercih edildi?_\n\n## Etkilenen Taraflar\n_Bu karardan kimler/hangi ekipler etkilenecek?_\n- \n'
WHERE name='Karar Kaydı';

UPDATE wiki_page_templates SET content = E'# Doküman Kontrol Sayfası: \n\n**Doküman No:** \n**Versiyon:** \n**Sahip:** \n**Onay Tarihi:** \n**Gözden Geçirme Sıklığı:** \n\n## Amaç\n_Bu doküman ne için var, kim için yazıldı?_\n\n## Kapsam\n_Bu dokümanın kapsadığı ve KAPSAMADIĞI alanlar._\n\n## Onay Zinciri\n| Rol | İsim | Tarih | Durum |\n|---|---|---|---|\n| Hazırlayan | | | |\n| Kontrol Eden | | | |\n| Onaylayan | | | |\n\n## Değişiklik Geçmişi\n| Versiyon | Tarih | Değişiklik | Yapan |\n|---|---|---|---|\n| 1.0 | | İlk yayın | |\n'
WHERE name='Doküman Kontrol Sayfası';

UPDATE wiki_page_templates SET content = E'# Proje Planı: \n\n**Proje Yöneticisi:** \n**Başlangıç / Bitiş:** \n\n## Amaç ve Kapsam\n_Bu proje ne için yapılıyor, hangi iş sonucunu hedefliyor?_\n\n**Kapsamda (Must-have):**\n- \n\n**Olsa iyi olur (Nice-to-have):**\n- \n\n**Kapsam Dışı:**\n- \n\n## Kilometre Taşları\n| Kilometre Taşı | Sahibi | Hedef Tarih | Durum |\n|---|---|---|---|\n| | | | Planlandı |\n\n## Ekip ve Roller\n| Rol | Kişi |\n|---|---|\n| Proje Yöneticisi | |\n| Sponsor | |\n\n## Riskler\n| Risk | Olasılık | Etki | Önlem |\n|---|---|---|---|\n| | | | |\n\n## Paydaşlar\n_Bu projeden etkilenen ya da bilgilendirilmesi gereken kişi/ekipler._\n- \n\n## İletişim Planı\n_Durum güncellemeleri kime, ne sıklıkla, hangi kanaldan iletilecek?_\n'
WHERE name='Proje Planı';
