-- 055_wiki_templates_final_eight.sql
-- Kullanıcı isteği: şablon listesi TAM olarak şu 8'e indirilsin, bu sırada:
-- Toplantı Notu, Analiz, BRD, FRD, Retro, UAT, Risk, Diğer.
-- "Diğerlerine gerek yok" — önceki 18 şablonun geri kalanı tamamen
-- kaldırılıyor. BRD/FRD/UAT gerçek iş analizi pratiğine göre (BRD vs
-- FRD ayrımı, UAT test senaryosu tablosu) araştırılıp yazıldı;
-- Analiz/Retro/Risk önceki zengin içerikleriyle korunup yeniden
-- adlandırıldı.
DELETE FROM wiki_page_templates;

INSERT INTO wiki_page_templates (name, content, sort_order, created_by) VALUES
('Toplantı Notu', E'# Toplantı Notu: \n\n**Tarih:** \n**Katılımcılar:** \n\n## Gündem\n_Toplantı öncesi belirlenen konu başlıkları._\n- \n\n## Notlar\n_Görüşme sırasında alınan notlar, tartışılan konular._\n\n\n## Kararlar\n_Bu toplantıda netleşen kararlar._\n- \n\n## Aksiyon Maddeleri\n| Aksiyon | Sorumlu | Hedef Tarih |\n|---|---|---|\n| | | |\n', 1, NULL),

('Analiz', E'# Analiz: \n\n**Konu:** \n**Analiz Tarihi:** \n**Analiz Eden:** \n\n> Bu sayfa bir durumu, sistemi ya da öneriyi tarafsız bir gözle değerlendirmek için kullanılır.\n\n## Mevcut Durum Özeti\n_Şu anda nerede olduğumuzu, neyin nasıl işlediğini kısaca özetleyin._\n\n\n## Kapsam\n_Bu analiz neyi kapsıyor, neyi kapsamıyor?_\n\n\n## Bulgular\n_Veriye/gözleme dayalı somut bulgular._\n- \n\n## Değerlendirme Tablosu\n| Konu | Mevcut Durum | Sorun/Fırsat | Etki |\n|---|---|---|---|\n| | | | |\n\n## Riskler ve Açık Sorular\n- \n\n## Sonuç ve Öneriler\n_Bu analizden çıkan somut aksiyon önerileri, gerekçesiyle birlikte._\n', 2, NULL),

('BRD', E'# BRD (İş Gereksinimleri Dokümanı): \n\n**Proje:** \n**Hazırlayan:** \n**Versiyon:** 1.0\n**Durum:** Taslak\n\n> BRD, işin NE istediğini anlatır ("what") — NASIL yapılacağını (fonksiyonel detayları) FRD''ye bırakır.\n\n## Yönetici Özeti\n_2-3 cümlede: bu proje/değişiklik ne için yapılıyor, en önemli iş sonucu ne?_\n\n## Arka Plan\n_Bu ihtiyacın ortaya çıkmasına sebep olan iş durumu, problem ya da fırsat._\n\n## İş Hedefleri ve Amaçları\n_Bu proje başarılı olursa iş tarafında ne değişecek? Mümkünse ölçülebilir hedefler yazın._\n- \n\n## Kapsam\n**Kapsamda:**\n- \n\n**Kapsam Dışı:**\n- \n\n## Paydaşlar\n| Rol | Kişi | İlgi Alanı |\n|---|---|---|\n| İş Sahibi (Business Owner) | | |\n| Proje Sponsoru | | |\n\n## İş Gereksinimleri\n_Her gereksinim, izlenebilirlik için bir kod alır (BR-001, BR-002...)._\n| Kod | Gereksinim | Öncelik | Gerekçe |\n|---|---|---|---|\n| BR-001 | | Yüksek/Orta/Düşük | |\n\n## Varsayımlar ve Kısıtlar\n- \n\n## Başarı Kriterleri\n_Bu proje ne zaman "başarılı" sayılacak?_\n- \n\n## Riskler\n| Risk | Etki | Önlem |\n|---|---|---|\n| | | |\n', 3, NULL),

('FRD', E'# FRD (Fonksiyonel Gereksinimler Dokümanı): \n\n**İlgili BRD:** \n**Hazırlayan:** \n**Versiyon:** 1.0\n**Durum:** Taslak\n\n> FRD, BRD''deki iş gereksinimlerinin sistemde NASIL karşılanacağını ("how") tanımlar; SIT/UAT test senaryolarının temel kaynağıdır.\n\n## Amaç ve Kapsam\n_Bu doküman hangi sistemi/modülü kapsıyor?_\n\n## Kullanıcı Rolleri\n| Rol | Yetkiler/Erişim |\n|---|---|\n| | |\n\n## Fonksiyonel Gereksinimler\n_Her gereksinim, ilişkili olduğu BRD maddesine (BR-xxx) referans verir._\n| Kod | Gereksinim Açıklaması | İlgili BR | Öncelik |\n|---|---|---|---|\n| FR-001 | | BR-001 | Yüksek |\n\n## Kullanım Senaryoları (Use Cases)\n### UC-001: \n**Aktör:** \n**Ön Koşul:** \n**Ana Akış:**\n1. \n2. \n**Alternatif Akış:**\n- \n**Son Koşul:** \n\n## Fonksiyonel Olmayan Gereksinimler\n_Performans, güvenlik, ölçeklenebilirlik, kullanılabilirlik gibi kalite nitelikleri._\n| Kategori | Gereksinim |\n|---|---|\n| Performans | |\n| Güvenlik | |\n\n## Veri Gereksinimleri\n_Yeni/değişen veri alanları, kaynakları, saklama kuralları._\n\n\n## Kabul Kriterleri\n_Bu gereksinimlerin "tamamlandı" sayılması için karşılanması gereken koşullar — UAT senaryolarının temelini oluşturur._\n- \n', 4, NULL),

('Retro', E'# Retro: \n\n**Sprint/Dönem:** \n**Tarih:** \n**Katılımcılar:** \n\n## Amaç\n_Bu retrospektifin amacını bir cümleyle özetleyin — ör. "Son sprint''teki teslimat gecikmelerinin kök nedenini bulmak."_\n\n## Arka Plan\n_Bu dönemde neler teslim edildi/yaşandı? 2-3 cümlelik kısa bir özet, herkesin hafızasını tazelemesi için._\n\n## Beğendiklerim (Loved)\n_Bu dönem keyif aldığımız, tekrar etmek istediğimiz şeyler._\n- \n\n## Öğrendiklerim (Learned)\n_Yeni fark ettiğimiz, öğrendiğimiz şeyler._\n- \n\n## Eksik Kalanlar (Lacked)\n_İhtiyaç duyduğumuz ama sahip olmadığımız şeyler (araç, bilgi, zaman, destek)._\n- \n\n## Özlediklerim (Longed for)\n_Keşke olsaydı dediğimiz şeyler._\n- \n\n## Aksiyon Maddeleri\n| Aksiyon | Sorumlu | Hedef Tarih | Durum |\n|---|---|---|---|\n| | | | Açık |\n\n## Kapanış Notları\n_Bir sonraki dönemde neyi farklı yapacağız?_\n', 5, NULL),

('UAT', E'# UAT (Kullanıcı Kabul Testi) Planı: \n\n**Proje/Özellik:** \n**Test Dönemi:** \n**Test Sorumlusu:** \n**İlgili FRD:** \n\n> UAT''ın amacı, sistemin GERÇEK kullanıcı ihtiyaçlarını (FRD''deki kabul kriterlerini) karşıladığını iş tarafının kendisinin doğrulamasıdır — teknik test (SIT) ile karıştırılmamalıdır.\n\n## Kapsam\n**Test edilecek:**\n- \n\n**Kapsam dışı:**\n- \n\n## Test Katılımcıları\n| Rol | Kişi |\n|---|---|\n| İş Kullanıcısı (Tester) | |\n| Onaylayan (Sign-off) | |\n\n## Test Senaryoları\n| # | Senaryo | Adımlar | Beklenen Sonuç | Gerçekleşen | Durum | Test Eden |\n|---|---|---|---|---|---|---|\n| 1 | | | | | Bekliyor | |\n\n## Bulunan Hatalar\n| # | Açıklama | Ciddiyet | Durum | İlgili Test # |\n|---|---|---|---|---|\n| | | | Açık | |\n\n## Çıkış Kriterleri (Sign-off)\n_UAT''ın "geçti" sayılması için karşılanması gereken koşullar (ör. kritik senaryoların %100''ü, yüksek öncelikli hataların kapanmış olması)._\n- \n\n## Onay\n| Rol | İsim | Tarih | Karar |\n|---|---|---|---|\n| İş Sahibi | | | Onaylandı / Reddedildi |\n', 6, NULL),

('Risk', E'# Risk Kaydı: \n\n**Proje:** \n**Güncelleme Tarihi:** \n\n> Olasılık ve Etki için 1 (Düşük) - 5 (Çok Yüksek) arası bir puanlama önerilir; Skor = Olasılık × Etki.\n\n| # | Risk Tanımı | Kategori | Olasılık (1-5) | Etki (1-5) | Skor | Önlem/Aksiyon | Sahibi | Durum |\n|---|---|---|---|---|---|---|---|---|\n| 1 | | Teknik / Zaman / Bütçe / Kaynak | | | | | | Açık |\n\n## Yüksek Öncelikli Riskler (Skor ≥ 15)\n_Yukarıdaki tablodan en kritik olanları buraya taşıyıp detaylandırın._\n\n\n## Kapatılan Riskler\n_Artık geçerli olmayan ya da gerçekleşmeyen riskler, ne zaman ve neden kapatıldığıyla birlikte._\n', 7, NULL),

('Diğer', E'# \n\n**Tarih:** \n**Hazırlayan:** \n\n## Amaç\n_Bu sayfa ne için var?_\n\n## İçerik\n\n\n## Notlar\n', 8, NULL);
